apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe
spec:
  selector:
    matchLabels:
      app: recipe
  replicas: 1
  template:
    metadata:
      name: recipe
      labels:
        app: recipe
    spec:
      containers:
        - name: recipe
          image: recipe:latest
          command: [ "python","main.py"]
          ports:
            - containerPort: 5008
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
          - name: recipe-data
            mountPath: /data/
          imagePullPolicy: IfNotPresent
      volumes:
      - name: recipe-data
        persistentVolumeClaim:
          claimName: recipe-data