apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
spec:
  selector:
    matchLabels:
      app: login
  replicas: 1
  template:
    metadata:
      name: login
      labels:
        app: login
    spec:
      containers:
        - name: login
          image: login:latest
          command: [ "python","main.py","flask","run","--host","0.0.0.0","--port","5000:5000" ]
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          imagePullPolicy: IfNotPresent