apiVersion: apps/v1
kind: Deployment
metadata:
  name: submitdb
spec:
  selector:
    matchLabels:
      app: submitdb
  replicas: 1
  template:
    metadata:
      name: submitdb
      labels:
        app: submitdb
    spec:
      containers:
        - name: submitdb
          image: submitdb:latest
          command: [ "python","main.py"]
          ports:
            - containerPort: 5001
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
          - name: recipe-data
            mountPath: /data/
          imagePullPolicy: IfNotPresent
      volumes:
      - name: recipe-data
        persistentVolumeClaim:
          claimName: recipe-data